### ISSUE TITLE
Updating status collapses details

### ISSUE THREAD

**Issue by jessstubenbord** [lm-tools/your-work-search#44]
Updating the status of a role collapses the details, hiding what has just been interacted with. The page position is also reset to the top.

**Comment by nathancashmoredwp** [comment]
Being addressed as part of OR-85.

**Comment by nathancashmoredwp** [comment]
@jessstubenbord can you take a look at #79 when its deployed, this that answers the position reset issue.

**Comment by nathancashmoredwp** [comment]
i've also put the CHEF data on it so you should be able to see via
https://your-work-search-pr-79.herokuapp.com/CHEF-123
