### ISSUE TITLE
your-work-search/* allows new id creation but doesn't show introduction speedbump

### ISSUE THREAD

**Issue by jessstubenbord** [lm-tools/your-work-search#99]
Visiting your-work-search/* allows new id creation but doesn't show introduction speedbump.

might not be a serious issue, but wasn't expected by me

**Comment by nathancashmoredwp** [comment]
Discussed at length and decided validation of UUID was important but based on entrypoint (e.g. with ?id=<UUID>) showing the introduction page not a problem.
